BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[users] ADD [isActive] BIT NOT NULL CONSTRAINT [users_isActive_df] DEFAULT 1,
[role] NVARCHAR(20) NOT NULL CONSTRAINT [users_role_df] DEFAULT 'USER';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
